version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    networks:
      - my_elk
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      #- cluster.initial_master_nodes=elasticsearch
      #- cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      - ./esdata/log:/usr/share/elasticsearch/logs
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    networks:
      - my_elk
      - my_nginx
    environment:
      - ELASTICSEARCH_URL="http://elasticsearch:9200"
      #- XPACK.REPORTING.ENABLED=false
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5661:5601
    depends_on:
      - elasticsearch

networks:
  my_elk:
    external:
      name: my_elk
  my_nginx:
    external:
      name: my_nginx
